/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers.index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedFeesIndexRouteImport } from './routes/_authenticated/fees.index'
import { Route as AuthenticatedExaminationsIndexRouteImport } from './routes/_authenticated/examinations.index'
import { Route as AuthenticatedTeachersTeacherIdRouteImport } from './routes/_authenticated/teachers.$teacherId'
import { Route as AuthenticatedStudentsPromoteRouteImport } from './routes/_authenticated/students.promote'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students.new'
import { Route as AuthenticatedStudentsImportRouteImport } from './routes/_authenticated/students.import'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedFeesSettingsRouteImport } from './routes/_authenticated/fees.settings'
import { Route as AuthenticatedFeesImportRouteImport } from './routes/_authenticated/fees.import'
import { Route as AuthenticatedFeesConcessionsRouteImport } from './routes/_authenticated/fees.concessions'
import { Route as AuthenticatedExaminationsSubjectsRouteImport } from './routes/_authenticated/examinations.subjects'
import { Route as AuthenticatedExaminationsGradeScalesRouteImport } from './routes/_authenticated/examinations.grade-scales'
import { Route as AuthenticatedFeesStructuresIndexRouteImport } from './routes/_authenticated/fees.structures.index'
import { Route as AuthenticatedFeesReceiptsIndexRouteImport } from './routes/_authenticated/fees.receipts.index'
import { Route as AuthenticatedFeesCollectIndexRouteImport } from './routes/_authenticated/fees.collect.index'
import { Route as AuthenticatedExaminationsPatternsIndexRouteImport } from './routes/_authenticated/examinations.patterns.index'
import { Route as AuthenticatedStudentsStudentIdEditRouteImport } from './routes/_authenticated/students.$studentId.edit'
import { Route as AuthenticatedFeesStructuresStructureIdRouteImport } from './routes/_authenticated/fees.structures.$structureId'
import { Route as AuthenticatedFeesReportViewRouteImport } from './routes/_authenticated/fees.report.$view'
import { Route as AuthenticatedFeesReceiptsPaymentIdRouteImport } from './routes/_authenticated/fees.receipts.$paymentId'
import { Route as AuthenticatedFeesCollectStudentIdRouteImport } from './routes/_authenticated/fees.collect.$studentId'
import { Route as AuthenticatedExaminationsPatternsPatternIdRouteImport } from './routes/_authenticated/examinations.patterns.$patternId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesIndexRoute = AuthenticatedFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExaminationsIndexRoute =
  AuthenticatedExaminationsIndexRouteImport.update({
    id: '/examinations/',
    path: '/examinations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersTeacherIdRoute =
  AuthenticatedTeachersTeacherIdRouteImport.update({
    id: '/teachers/$teacherId',
    path: '/teachers/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsPromoteRoute =
  AuthenticatedStudentsPromoteRouteImport.update({
    id: '/students/promote',
    path: '/students/promote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsImportRoute =
  AuthenticatedStudentsImportRouteImport.update({
    id: '/students/import',
    path: '/students/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesSettingsRoute =
  AuthenticatedFeesSettingsRouteImport.update({
    id: '/fees/settings',
    path: '/fees/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesImportRoute = AuthenticatedFeesImportRouteImport.update({
  id: '/fees/import',
  path: '/fees/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesConcessionsRoute =
  AuthenticatedFeesConcessionsRouteImport.update({
    id: '/fees/concessions',
    path: '/fees/concessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExaminationsSubjectsRoute =
  AuthenticatedExaminationsSubjectsRouteImport.update({
    id: '/examinations/subjects',
    path: '/examinations/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExaminationsGradeScalesRoute =
  AuthenticatedExaminationsGradeScalesRouteImport.update({
    id: '/examinations/grade-scales',
    path: '/examinations/grade-scales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesStructuresIndexRoute =
  AuthenticatedFeesStructuresIndexRouteImport.update({
    id: '/fees/structures/',
    path: '/fees/structures/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesReceiptsIndexRoute =
  AuthenticatedFeesReceiptsIndexRouteImport.update({
    id: '/fees/receipts/',
    path: '/fees/receipts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesCollectIndexRoute =
  AuthenticatedFeesCollectIndexRouteImport.update({
    id: '/fees/collect/',
    path: '/fees/collect/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExaminationsPatternsIndexRoute =
  AuthenticatedExaminationsPatternsIndexRouteImport.update({
    id: '/examinations/patterns/',
    path: '/examinations/patterns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdEditRoute =
  AuthenticatedStudentsStudentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedStudentsStudentIdRoute,
  } as any)
const AuthenticatedFeesStructuresStructureIdRoute =
  AuthenticatedFeesStructuresStructureIdRouteImport.update({
    id: '/fees/structures/$structureId',
    path: '/fees/structures/$structureId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesReportViewRoute =
  AuthenticatedFeesReportViewRouteImport.update({
    id: '/fees/report/$view',
    path: '/fees/report/$view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesReceiptsPaymentIdRoute =
  AuthenticatedFeesReceiptsPaymentIdRouteImport.update({
    id: '/fees/receipts/$paymentId',
    path: '/fees/receipts/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesCollectStudentIdRoute =
  AuthenticatedFeesCollectStudentIdRouteImport.update({
    id: '/fees/collect/$studentId',
    path: '/fees/collect/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExaminationsPatternsPatternIdRoute =
  AuthenticatedExaminationsPatternsPatternIdRouteImport.update({
    id: '/examinations/patterns/$patternId',
    path: '/examinations/patterns/$patternId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/examinations/grade-scales': typeof AuthenticatedExaminationsGradeScalesRoute
  '/examinations/subjects': typeof AuthenticatedExaminationsSubjectsRoute
  '/fees/concessions': typeof AuthenticatedFeesConcessionsRoute
  '/fees/import': typeof AuthenticatedFeesImportRoute
  '/fees/settings': typeof AuthenticatedFeesSettingsRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteWithChildren
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students/promote': typeof AuthenticatedStudentsPromoteRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/examinations/': typeof AuthenticatedExaminationsIndexRoute
  '/fees/': typeof AuthenticatedFeesIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/examinations/patterns/$patternId': typeof AuthenticatedExaminationsPatternsPatternIdRoute
  '/fees/collect/$studentId': typeof AuthenticatedFeesCollectStudentIdRoute
  '/fees/receipts/$paymentId': typeof AuthenticatedFeesReceiptsPaymentIdRoute
  '/fees/report/$view': typeof AuthenticatedFeesReportViewRoute
  '/fees/structures/$structureId': typeof AuthenticatedFeesStructuresStructureIdRoute
  '/students/$studentId/edit': typeof AuthenticatedStudentsStudentIdEditRoute
  '/examinations/patterns/': typeof AuthenticatedExaminationsPatternsIndexRoute
  '/fees/collect/': typeof AuthenticatedFeesCollectIndexRoute
  '/fees/receipts/': typeof AuthenticatedFeesReceiptsIndexRoute
  '/fees/structures/': typeof AuthenticatedFeesStructuresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/examinations/grade-scales': typeof AuthenticatedExaminationsGradeScalesRoute
  '/examinations/subjects': typeof AuthenticatedExaminationsSubjectsRoute
  '/fees/concessions': typeof AuthenticatedFeesConcessionsRoute
  '/fees/import': typeof AuthenticatedFeesImportRoute
  '/fees/settings': typeof AuthenticatedFeesSettingsRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteWithChildren
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students/promote': typeof AuthenticatedStudentsPromoteRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/examinations': typeof AuthenticatedExaminationsIndexRoute
  '/fees': typeof AuthenticatedFeesIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/examinations/patterns/$patternId': typeof AuthenticatedExaminationsPatternsPatternIdRoute
  '/fees/collect/$studentId': typeof AuthenticatedFeesCollectStudentIdRoute
  '/fees/receipts/$paymentId': typeof AuthenticatedFeesReceiptsPaymentIdRoute
  '/fees/report/$view': typeof AuthenticatedFeesReportViewRoute
  '/fees/structures/$structureId': typeof AuthenticatedFeesStructuresStructureIdRoute
  '/students/$studentId/edit': typeof AuthenticatedStudentsStudentIdEditRoute
  '/examinations/patterns': typeof AuthenticatedExaminationsPatternsIndexRoute
  '/fees/collect': typeof AuthenticatedFeesCollectIndexRoute
  '/fees/receipts': typeof AuthenticatedFeesReceiptsIndexRoute
  '/fees/structures': typeof AuthenticatedFeesStructuresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/examinations/grade-scales': typeof AuthenticatedExaminationsGradeScalesRoute
  '/_authenticated/examinations/subjects': typeof AuthenticatedExaminationsSubjectsRoute
  '/_authenticated/fees/concessions': typeof AuthenticatedFeesConcessionsRoute
  '/_authenticated/fees/import': typeof AuthenticatedFeesImportRoute
  '/_authenticated/fees/settings': typeof AuthenticatedFeesSettingsRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteWithChildren
  '/_authenticated/students/import': typeof AuthenticatedStudentsImportRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/students/promote': typeof AuthenticatedStudentsPromoteRoute
  '/_authenticated/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/_authenticated/examinations/': typeof AuthenticatedExaminationsIndexRoute
  '/_authenticated/fees/': typeof AuthenticatedFeesIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/examinations/patterns/$patternId': typeof AuthenticatedExaminationsPatternsPatternIdRoute
  '/_authenticated/fees/collect/$studentId': typeof AuthenticatedFeesCollectStudentIdRoute
  '/_authenticated/fees/receipts/$paymentId': typeof AuthenticatedFeesReceiptsPaymentIdRoute
  '/_authenticated/fees/report/$view': typeof AuthenticatedFeesReportViewRoute
  '/_authenticated/fees/structures/$structureId': typeof AuthenticatedFeesStructuresStructureIdRoute
  '/_authenticated/students/$studentId/edit': typeof AuthenticatedStudentsStudentIdEditRoute
  '/_authenticated/examinations/patterns/': typeof AuthenticatedExaminationsPatternsIndexRoute
  '/_authenticated/fees/collect/': typeof AuthenticatedFeesCollectIndexRoute
  '/_authenticated/fees/receipts/': typeof AuthenticatedFeesReceiptsIndexRoute
  '/_authenticated/fees/structures/': typeof AuthenticatedFeesStructuresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/admissions'
    | '/attendance'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/examinations/grade-scales'
    | '/examinations/subjects'
    | '/fees/concessions'
    | '/fees/import'
    | '/fees/settings'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/students/promote'
    | '/teachers/$teacherId'
    | '/examinations/'
    | '/fees/'
    | '/students/'
    | '/teachers/'
    | '/examinations/patterns/$patternId'
    | '/fees/collect/$studentId'
    | '/fees/receipts/$paymentId'
    | '/fees/report/$view'
    | '/fees/structures/$structureId'
    | '/students/$studentId/edit'
    | '/examinations/patterns/'
    | '/fees/collect/'
    | '/fees/receipts/'
    | '/fees/structures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/admissions'
    | '/attendance'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/examinations/grade-scales'
    | '/examinations/subjects'
    | '/fees/concessions'
    | '/fees/import'
    | '/fees/settings'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/students/promote'
    | '/teachers/$teacherId'
    | '/examinations'
    | '/fees'
    | '/students'
    | '/teachers'
    | '/examinations/patterns/$patternId'
    | '/fees/collect/$studentId'
    | '/fees/receipts/$paymentId'
    | '/fees/report/$view'
    | '/fees/structures/$structureId'
    | '/students/$studentId/edit'
    | '/examinations/patterns'
    | '/fees/collect'
    | '/fees/receipts'
    | '/fees/structures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/admissions'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/examinations/grade-scales'
    | '/_authenticated/examinations/subjects'
    | '/_authenticated/fees/concessions'
    | '/_authenticated/fees/import'
    | '/_authenticated/fees/settings'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/import'
    | '/_authenticated/students/new'
    | '/_authenticated/students/promote'
    | '/_authenticated/teachers/$teacherId'
    | '/_authenticated/examinations/'
    | '/_authenticated/fees/'
    | '/_authenticated/students/'
    | '/_authenticated/teachers/'
    | '/_authenticated/examinations/patterns/$patternId'
    | '/_authenticated/fees/collect/$studentId'
    | '/_authenticated/fees/receipts/$paymentId'
    | '/_authenticated/fees/report/$view'
    | '/_authenticated/fees/structures/$structureId'
    | '/_authenticated/students/$studentId/edit'
    | '/_authenticated/examinations/patterns/'
    | '/_authenticated/fees/collect/'
    | '/_authenticated/fees/receipts/'
    | '/_authenticated/fees/structures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/': {
      id: '/_authenticated/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof AuthenticatedFeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations/': {
      id: '/_authenticated/examinations/'
      path: '/examinations'
      fullPath: '/examinations/'
      preLoaderRoute: typeof AuthenticatedExaminationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/$teacherId': {
      id: '/_authenticated/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedTeachersTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/promote': {
      id: '/_authenticated/students/promote'
      path: '/students/promote'
      fullPath: '/students/promote'
      preLoaderRoute: typeof AuthenticatedStudentsPromoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/import': {
      id: '/_authenticated/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AuthenticatedStudentsImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/settings': {
      id: '/_authenticated/fees/settings'
      path: '/fees/settings'
      fullPath: '/fees/settings'
      preLoaderRoute: typeof AuthenticatedFeesSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/import': {
      id: '/_authenticated/fees/import'
      path: '/fees/import'
      fullPath: '/fees/import'
      preLoaderRoute: typeof AuthenticatedFeesImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/concessions': {
      id: '/_authenticated/fees/concessions'
      path: '/fees/concessions'
      fullPath: '/fees/concessions'
      preLoaderRoute: typeof AuthenticatedFeesConcessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations/subjects': {
      id: '/_authenticated/examinations/subjects'
      path: '/examinations/subjects'
      fullPath: '/examinations/subjects'
      preLoaderRoute: typeof AuthenticatedExaminationsSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations/grade-scales': {
      id: '/_authenticated/examinations/grade-scales'
      path: '/examinations/grade-scales'
      fullPath: '/examinations/grade-scales'
      preLoaderRoute: typeof AuthenticatedExaminationsGradeScalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/structures/': {
      id: '/_authenticated/fees/structures/'
      path: '/fees/structures'
      fullPath: '/fees/structures/'
      preLoaderRoute: typeof AuthenticatedFeesStructuresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/receipts/': {
      id: '/_authenticated/fees/receipts/'
      path: '/fees/receipts'
      fullPath: '/fees/receipts/'
      preLoaderRoute: typeof AuthenticatedFeesReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/collect/': {
      id: '/_authenticated/fees/collect/'
      path: '/fees/collect'
      fullPath: '/fees/collect/'
      preLoaderRoute: typeof AuthenticatedFeesCollectIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations/patterns/': {
      id: '/_authenticated/examinations/patterns/'
      path: '/examinations/patterns'
      fullPath: '/examinations/patterns/'
      preLoaderRoute: typeof AuthenticatedExaminationsPatternsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId/edit': {
      id: '/_authenticated/students/$studentId/edit'
      path: '/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdEditRouteImport
      parentRoute: typeof AuthenticatedStudentsStudentIdRoute
    }
    '/_authenticated/fees/structures/$structureId': {
      id: '/_authenticated/fees/structures/$structureId'
      path: '/fees/structures/$structureId'
      fullPath: '/fees/structures/$structureId'
      preLoaderRoute: typeof AuthenticatedFeesStructuresStructureIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/report/$view': {
      id: '/_authenticated/fees/report/$view'
      path: '/fees/report/$view'
      fullPath: '/fees/report/$view'
      preLoaderRoute: typeof AuthenticatedFeesReportViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/receipts/$paymentId': {
      id: '/_authenticated/fees/receipts/$paymentId'
      path: '/fees/receipts/$paymentId'
      fullPath: '/fees/receipts/$paymentId'
      preLoaderRoute: typeof AuthenticatedFeesReceiptsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/collect/$studentId': {
      id: '/_authenticated/fees/collect/$studentId'
      path: '/fees/collect/$studentId'
      fullPath: '/fees/collect/$studentId'
      preLoaderRoute: typeof AuthenticatedFeesCollectStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations/patterns/$patternId': {
      id: '/_authenticated/examinations/patterns/$patternId'
      path: '/examinations/patterns/$patternId'
      fullPath: '/examinations/patterns/$patternId'
      preLoaderRoute: typeof AuthenticatedExaminationsPatternsPatternIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedStudentsStudentIdRouteChildren {
  AuthenticatedStudentsStudentIdEditRoute: typeof AuthenticatedStudentsStudentIdEditRoute
}

const AuthenticatedStudentsStudentIdRouteChildren: AuthenticatedStudentsStudentIdRouteChildren =
  {
    AuthenticatedStudentsStudentIdEditRoute:
      AuthenticatedStudentsStudentIdEditRoute,
  }

const AuthenticatedStudentsStudentIdRouteWithChildren =
  AuthenticatedStudentsStudentIdRoute._addFileChildren(
    AuthenticatedStudentsStudentIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedExaminationsGradeScalesRoute: typeof AuthenticatedExaminationsGradeScalesRoute
  AuthenticatedExaminationsSubjectsRoute: typeof AuthenticatedExaminationsSubjectsRoute
  AuthenticatedFeesConcessionsRoute: typeof AuthenticatedFeesConcessionsRoute
  AuthenticatedFeesImportRoute: typeof AuthenticatedFeesImportRoute
  AuthenticatedFeesSettingsRoute: typeof AuthenticatedFeesSettingsRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRouteWithChildren
  AuthenticatedStudentsImportRoute: typeof AuthenticatedStudentsImportRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedStudentsPromoteRoute: typeof AuthenticatedStudentsPromoteRoute
  AuthenticatedTeachersTeacherIdRoute: typeof AuthenticatedTeachersTeacherIdRoute
  AuthenticatedExaminationsIndexRoute: typeof AuthenticatedExaminationsIndexRoute
  AuthenticatedFeesIndexRoute: typeof AuthenticatedFeesIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedExaminationsPatternsPatternIdRoute: typeof AuthenticatedExaminationsPatternsPatternIdRoute
  AuthenticatedFeesCollectStudentIdRoute: typeof AuthenticatedFeesCollectStudentIdRoute
  AuthenticatedFeesReceiptsPaymentIdRoute: typeof AuthenticatedFeesReceiptsPaymentIdRoute
  AuthenticatedFeesReportViewRoute: typeof AuthenticatedFeesReportViewRoute
  AuthenticatedFeesStructuresStructureIdRoute: typeof AuthenticatedFeesStructuresStructureIdRoute
  AuthenticatedExaminationsPatternsIndexRoute: typeof AuthenticatedExaminationsPatternsIndexRoute
  AuthenticatedFeesCollectIndexRoute: typeof AuthenticatedFeesCollectIndexRoute
  AuthenticatedFeesReceiptsIndexRoute: typeof AuthenticatedFeesReceiptsIndexRoute
  AuthenticatedFeesStructuresIndexRoute: typeof AuthenticatedFeesStructuresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedExaminationsGradeScalesRoute:
    AuthenticatedExaminationsGradeScalesRoute,
  AuthenticatedExaminationsSubjectsRoute:
    AuthenticatedExaminationsSubjectsRoute,
  AuthenticatedFeesConcessionsRoute: AuthenticatedFeesConcessionsRoute,
  AuthenticatedFeesImportRoute: AuthenticatedFeesImportRoute,
  AuthenticatedFeesSettingsRoute: AuthenticatedFeesSettingsRoute,
  AuthenticatedStudentsStudentIdRoute:
    AuthenticatedStudentsStudentIdRouteWithChildren,
  AuthenticatedStudentsImportRoute: AuthenticatedStudentsImportRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedStudentsPromoteRoute: AuthenticatedStudentsPromoteRoute,
  AuthenticatedTeachersTeacherIdRoute: AuthenticatedTeachersTeacherIdRoute,
  AuthenticatedExaminationsIndexRoute: AuthenticatedExaminationsIndexRoute,
  AuthenticatedFeesIndexRoute: AuthenticatedFeesIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedExaminationsPatternsPatternIdRoute:
    AuthenticatedExaminationsPatternsPatternIdRoute,
  AuthenticatedFeesCollectStudentIdRoute:
    AuthenticatedFeesCollectStudentIdRoute,
  AuthenticatedFeesReceiptsPaymentIdRoute:
    AuthenticatedFeesReceiptsPaymentIdRoute,
  AuthenticatedFeesReportViewRoute: AuthenticatedFeesReportViewRoute,
  AuthenticatedFeesStructuresStructureIdRoute:
    AuthenticatedFeesStructuresStructureIdRoute,
  AuthenticatedExaminationsPatternsIndexRoute:
    AuthenticatedExaminationsPatternsIndexRoute,
  AuthenticatedFeesCollectIndexRoute: AuthenticatedFeesCollectIndexRoute,
  AuthenticatedFeesReceiptsIndexRoute: AuthenticatedFeesReceiptsIndexRoute,
  AuthenticatedFeesStructuresIndexRoute: AuthenticatedFeesStructuresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
